### ISSUE TITLE
Error and requirements

### ISSUE THREAD

**Issue by jcarles** [xiaoyuan1996/AMFMN#3]
Hello,
I'm trying to execute your code but I'm getting errors:

Current lr: 0.0002
Traceback (most recent call last):
  File "train.py", line 209, in <module>
    main(update_options)
  File "train.py", line 99, in main
    engine.train(train_loader, model, optimizer, epoch, opt=options)
  File "/home/jbadia/AMFMN/AMFMN/engine.py", line 52, in train
    scores = model(input_visual, input_text, lengths)
  File "/home/jbadia/anaconda3/envs/amfmn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jbadia/AMFMN/AMFMN/layers/AMFMN.py", line 44, in forward

Could it be a problem of versions?
Do you have a requirements file with exact versions?

Thank you very much

**Comment by xiaoyuan1996** [comment]
May be the env error.
We suggest you to run the code of https://github.com/xiaoyuan1996/GaLR , which has the better performance

**Comment by jcarles** [comment]
However, if I want to change the dataset you use by another dataset we need to implement your DREA mechanism? Is it included in your github repo?
Thanks a lot,
